### ISSUE TITLE
Low GPU Utilization (27% Peak) with Default Config and CUDA OOM When Adjusting Batch Size on RTX 3090

### ISSUE THREAD

**Issue by Crescent-cc** [liuQuan98/EYOC#6]
Environment:​​

GPU: NVIDIA GeForce RTX 3090 (32GB VRAM)
CPU: 4-core processor

Issue Description:​​
When running the training script with default configurations (batch_size=8), GPU utilization peaks at only 27% during model training. 

I change :
export BATCH_SIZE=${BATCH_SIZE:-16}             
export ITER_SIZE=${ITER_SIZE:-2}                 
export MODEL_N_OUT=${MODEL_N_OUT:-16}           

and：
 Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 23.69 GiB total capacity; 16.91 GiB already allocated; 1.94 GiB free; 20.22 GiB reserved in total by PyTorch)

I recognize that as a beginner in deep learning, I may have overlooked some fundamental configurations. I sincerely appreciate you taking time to review this issue and would be grateful for any advice you could share.

**Comment by liuQuan98** [comment]
Sorry for the late reply.
Batch size tuning is relatively priliminary knowledge. Basically, you start from a large batch size that causes OOM, then reduce it using  dichotomy to find the largest possible batch size. Just for reference, my setting is given for 3090 24G.

**Comment by Crescent-cc** [comment]
感谢您的回复，以上问题已解决。
目前又遇到了新的问题：
当迭代到第七轮时，cuda出现报错，前面六轮是正常的。连续两次训练都遇到了这个问题，希望得到您的解答。
具体错误如下
04/21&nbsp;08:42:20&nbsp;Train Epoch:&nbsp;6&nbsp;[0/160], Current Loss:&nbsp;5.627e-01&nbsp;Pos:&nbsp;0.165&nbsp;Neg:&nbsp;0.398&nbsp;&nbsp;Data time:&nbsp;24.3948, Train time:&nbsp;1.8120, Iter time:&nbsp;26.2068&nbsp;&nbsp;Labeler IR:&nbsp;0.000
04/21&nbsp;08:44:11&nbsp;Train Epoch:&nbsp;6&nbsp;[40/160], Current Loss:&nbsp;5.697e-01&nbsp;Pos:&nbsp;0.181&nbsp;Neg:&nbsp;0.388&nbsp;Data time:&nbsp;0.8790, Train time:&nbsp;1.8968, Iter time:&nbsp;2.7758&nbsp;&nbsp;Labeler IR:&nbsp;0.000
04/21&nbsp;08:46:19&nbsp;Train Epoch:&nbsp;6&nbsp;[80/160], Current Loss:&nbsp;5.408e-01&nbsp;Pos:&nbsp;0.144&nbsp;Neg:&nbsp;0.397&nbsp;Data time:&nbsp;1.4259, Train time:&nbsp;1.7540, Iter time:&nbsp;3.1799&nbsp;&nbsp;Labeler IR:&nbsp;0.000
04/21&nbsp;08:48:28&nbsp;Train Epoch:&nbsp;6&nbsp;[120/160], Current Loss:&nbsp;5.345e-01&nbsp;Pos:&nbsp;0.135&nbsp;Neg:&nbsp;0.399&nbsp;&nbsp;Data time:&nbsp;1.5104, Train time:&nbsp;1.7311, Iter time:&nbsp;3.2416&nbsp;&nbsp;Labeler IR:&nbsp;0.000
04/21&nbsp;08:50:02&nbsp;Saving checkpoint: ./data/KittiContinuousFramePairDataset-v0.3/ContinuousCorrExtensionTrainer/ResUNetBN2C/SGD-lr3e-1-e200-b8i1-modelnout32/2025-04-21_07-52-55/checkpoint.pth ...
04/21&nbsp;08:50:03&nbsp;Resetting the data loader seed to&nbsp;0
04/21&nbsp;08:50:50&nbsp;Validation iter&nbsp;101&nbsp;/&nbsp;200&nbsp;: Data Loading Time:&nbsp;0.334, Feature Extraction Time:&nbsp;0.039, Matching Time:&nbsp;0.087, Loss:&nbsp;0.924, RTE:&nbsp;12.398, RRE:&nbsp;0.084, Hit Ratio:&nbsp;0.036, Feat Match Ratio:&nbsp;0.119
04/21&nbsp;08:51:33&nbsp;Final Loss:&nbsp;0.940, RTE:&nbsp;12.317, RRE:&nbsp;0.097, Hit Ratio:&nbsp;0.030, Feat Match Ratio:&nbsp;0.110
04/21&nbsp;08:51:34&nbsp;Current best val model with feat_match_ratio:&nbsp;0.13&nbsp;at epoch&nbsp;4
04/21&nbsp;08:51:34&nbsp;&nbsp;Epoch:&nbsp;7, LR: [0.26043765997401597]
Processing drive&nbsp;0
Processing drive&nbsp;1
Processing drive&nbsp;2
Processing drive&nbsp;3
Processing drive&nbsp;4
Processing drive&nbsp;5
Dataset extension for phase train:&nbsp;self.MAX_DIST=2
Data size for epoch&nbsp;7&nbsp;has been updated to:&nbsp;1286
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
04/21&nbsp;08:51:54&nbsp;Train Epoch:&nbsp;7&nbsp;[0/160], Current Loss:&nbsp;0.000e+00&nbsp;Pos:&nbsp;0.000&nbsp;Neg:&nbsp;0.000&nbsp;&nbsp;Data time:&nbsp;16.3043, Train time:&nbsp;2.0058, Iter time:&nbsp;18.3101&nbsp;&nbsp;Labeler IR:&nbsp;0.000
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
CUDA&nbsp;error:&nbsp;operation not supported when calling `cusparseCreate(handle)`
04/21&nbsp;08:53:19&nbsp;Train Epoch:&nbsp;7&nbsp;[40/160], Current Loss:&nbsp;0.000e+00&nbsp;Pos:&nbsp;0.000&nbsp;Neg:&nbsp;0.000&nbsp;Data time:&nbsp;0.3473, Train time:&nbsp;1.7695, Iter time:&nbsp;2.1168&nbsp;&nbsp;Labeler IR:&nbsp;0.000








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Quan ***@***.***&gt;; 
发送时间: 2025年4月22日(星期二) 凌晨0:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [liuQuan98/EYOC] Low GPU Utilization (27% Peak) with Default Config and CUDA OOM When Adjusting Batch Size on RTX 3090 (Issue #6)












   
Sorry for the late reply.
 Batch size tuning is relatively priliminary knowledge. Basically, you start from a large batch size that causes OOM, then reduce it using  dichotomy to find the largest possible batch size. Just for reference, my setting is given for 3090 24G.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  liuQuan98 left a comment (liuQuan98/EYOC#6)
 
Sorry for the late reply.
 Batch size tuning is relatively priliminary knowledge. Basically, you start from a large batch size that causes OOM, then reduce it using  dichotomy to find the largest possible batch size. Just for reference, my setting is given for 3090 24G.

**Comment by liuQuan98** [comment]
Please check if you have pytorch 1.6 and cuda 11.1, deviation from which might cause a problem.

**Comment by liuQuan98** [comment]
I recommend uncommenting the try block at EYOC/lib/trainer.py L1308, setting pair_min_dist to 2, and then rerunning the experiment. The problem should appear right away, so that you could debug it youself. Please update me for any fixes.
